### ISSUE TITLE
Failed to activate the angularjs-snippets package

### ISSUE THREAD

**Issue by jruhnke** [orlaqp/angular-snippets#3]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [angularjs-snippets](https://github.com/orlaqp/angular-snippets) package, v0.10.1

### Stack Trace

Failed to activate the angularjs-snippets package

```
At 'angularjs-snippets:toggle' is not a valid selector in C:\Users\jruhnke\.atom\packages\angularjs-snippets\package.json

Error: 'angularjs-snippets:toggle' is not a valid selector in C:\Users\jruhnke\.atom\packages\angularjs-snippets\package.json
    at exports.validateSelector (C:\Users\jruhnke\AppData\Local\atom\app-0.189.0\resources\app\src\selector-validator.js:36:13)
    at CommandRegistry.module.exports.CommandRegistry.add (C:\Users\jruhnke\AppData\Local\atom\app-0.189.0\resources\app\src\command-registry.js:48:9)
    at C:\Users\jruhnke\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:722:70
    at Package.module.exports.Package.subscribeToActivationCommands (C:\Users\jruhnke\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:751:11)
    at C:\Users\jruhnke\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:219:30
    at Package.module.exports.Package.measure (C:\Users\jruhnke\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:167:15)
    at Package.module.exports.Package.activate (C:\Users\jruhnke\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:214:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\jruhnke\AppData\Local\atom\app-0.189.0\resources\app\src\package-manager.js:461:21)
    at C:\Users\jruhnke\AppData\Local\atom\app-0.189.0\resources\app\src\package-manager.js:445:29
    at Config.module.exports.Config.transact (C:\Users\jruhnke\AppData\Local\atom\app-0.189.0\resources\app\src\config.js:343:16)
  at C:\Users\jruhnke\.atom\packages\angularjs-snippets\package.json:1:1
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-plus, v2.7.1
javascript-snippets, v1.0.0

# Dev
No dev packages
```

**Comment by orlaqp** [comment]
Hi there @jruhnke thanks for reporting the issue. I just released a new version with the fix. Can  you double check it and let me know if it works now?

Thanks.

**Comment by jruhnke** [comment]
Thank you it works great. Thanks again for the quick turn around.
